version: "3"
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: counter:latest
    command: ["./run.sh"]
    depends_on:
    - db
    ports:
    - "8080:8080"
    links:
    - db
    environment:
    - DB_DSN=postgresql://counter:counter@db:5432/counter
    - DB_HOST=db
    - DB_PORT=5432
    network_mode: bridge

  db:
    build:
      context: counter/db
      dockerfile: Dockerfile
    image: postgres_counter:latest

    network_mode: bridge